### ISSUE TITLE
Custom filetype

### ISSUE THREAD

**Issue by EdvardM** [Nivekk/KOS#288]
This is an excellent mod! Kudos for that.

I created a simple extension for writing more complex kOS scripts with sublime, https://github.com/EdvardM/kOS-Sublime/. However, to me it looks like only .txt files are supported. It would be great if there was another extension you could support, so that editors could auto-detect kerboscripts. 

Once again, thanks for the excellent mod that restored my interest in control system algorithms and stuff!

**Comment by edvardm** [comment]
Closing this, as there is plenty of well-supported modes for most popular editors already with appropriate extensions.
