### ISSUE TITLE
Can't focus on kOS Terminal

### ISSUE THREAD

**Issue by benjaminpwarren** [Nivekk/KOS#293]
I can't focus on the kOS terminal after hitting Launch and "Open Terminal". The window opens but it remains transparent and I can't focus it and therefore can't type in it. Am I missing something?

kOS 0.9.2 from kerbalspaceport.com and Kerbal Space Program 0.23. Test with and without and other mods installed.

**Comment by Nivekk** [comment]
This issue has now been fixed
